name: digital-orange-sites
# Deployment configuration for React/Vite app
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  run_command: npm run preview
  envs:
  - key: NODE_ENV
    value: production
  - key: NODE_VERSION
    value: 18.x
  - key: NPM_VERSION
    value: 10.8.2 