name: digital-orange-sites
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
  build_command: npm install && npm run build
  run_command: npm run preview
  envs:
  - key: NODE_ENV
    value: production 